export type LegalBlock =
  | { type: 'heading'; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'list'; items: string[] }
  | { type: 'contact'; name: string; email: string; website: string }

export interface LegalDoc {
  slug: string
  navLabel: string
  title: string
  effectiveDate: string | null
  blocks: LegalBlock[]
}

const h = (text: string): LegalBlock => ({ type: 'heading', text })
const p = (text: string): LegalBlock => ({ type: 'paragraph', text })
const ul = (items: string[]): LegalBlock => ({ type: 'list', items })
const contact = (email: string, website: string): LegalBlock => ({
  type: 'contact',
  name: 'Auzyem',
  email,
  website,
})

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: 'academic-integrity',
    navLabel: 'Academic Integrity',
    title: 'Academic Integrity & Responsible Use Policy',
    effectiveDate: '01/01/2025',
    blocks: [
      p('At Auzyem, we believe that learning happens through reflection, critical thinking and continual improvement. Our platform has been designed to support these principles by providing constructive feedback that helps users strengthen their own academic work.'),
      p('This Policy explains how the Service should and should not be used.'),

      h('1. Our Educational Purpose'),
      p('The Service provides automated academic feedback intended to help users evaluate and improve the quality of their own writing.'),
      p('The Service is designed to encourage independent learning by identifying areas where a manuscript may be strengthened, including matters such as:'),
      ul([
        'clarity of argument',
        'logical structure',
        'critical analysis',
        'evidence and supporting material',
        'coherence and organisation',
        'academic writing quality',
      ]),
      p('The Service is intended to complement, not replace, the learning process.'),

      h('2. What the Service Does Not Do'),
      p('The Service is not designed to:'),
      ul([
        'write assignments',
        'generate dissertations',
        'complete coursework',
        'produce essays on behalf of users',
        'replace academic supervision',
        'provide answers for assessments',
        'circumvent institutional academic integrity policies',
      ]),
      p('Users remain the sole author of all submitted work.'),

      h('3. Your Responsibilities'),
      p('When using the Service you agree that you will:'),
      ul([
        'submit only work that you are authorised to upload',
        'use the feedback to improve your own understanding',
        'exercise independent academic judgement',
        'ensure your use of the Service complies with the policies of your university or educational institution',
      ]),
      p('You remain solely responsible for all work submitted for assessment.'),

      h('4. Academic Integrity'),
      p('Many educational institutions have policies governing the use of artificial intelligence and other digital tools.'),
      p('It is your responsibility to understand and comply with the academic integrity requirements applicable to your course, institution and jurisdiction.'),
      p('Use of the Service does not imply that any university, college or educational institution approves or endorses its use.'),

      h('5. Responsible Use'),
      p('The Service should be used as a developmental learning resource.'),
      p('Examples of appropriate use include:'),
      ul([
        'reviewing an early draft before supervisor feedback',
        'identifying weaknesses in argument or structure',
        'improving critical analysis',
        'strengthening academic writing skills',
        'preparing for submission',
      ]),
      p('The Service should not be used to misrepresent authorship or falsely represent work as independently created where this would breach institutional rules.'),

      h('6. Prohibited Use'),
      p('You must not use the Service to:'),
      ul([
        'facilitate plagiarism',
        'impersonate another student or author',
        'submit work on behalf of another person without authorisation',
        'infringe copyright',
        'upload malicious software',
        'upload unlawful, offensive or harmful material',
        'interfere with the operation or security of the Service',
      ]),
      p('We reserve the right to suspend or terminate accounts involved in prohibited activities.'),

      h('7. Accuracy of Feedback'),
      p('Feedback generated by the Service is produced using artificial intelligence and automated analysis.'),
      p('While we strive to provide high-quality educational feedback:'),
      ul([
        'feedback may not identify every issue',
        'reasonable academics may hold different opinions',
        'feedback should not be regarded as definitive or authoritative',
      ]),
      p('The Service should be used alongside your own judgement and any guidance provided by your educational institution.'),

      h('8. Confidentiality of Your Work'),
      p('We recognise that academic work often represents many months of research and personal effort.'),
      p('Subject to our Privacy Policy, uploaded manuscripts are processed securely and are not published or made publicly available by us.'),
      p('Users should avoid uploading material containing confidential information belonging to third parties unless authorised to do so.'),

      h('9. Reporting Concerns'),
      p('If you believe the Service has produced inappropriate, inaccurate or harmful feedback, or if you believe another user is misusing the Service, please contact us.'),
      p('We continually improve the Service and welcome responsible feedback.'),

      h('10. Our Commitment'),
      p('We are committed to developing technology that supports education responsibly.'),
      p('Our goal is to help users become stronger writers, more critical thinkers and more confident researchers, while respecting academic integrity and the standards of educational institutions worldwide.'),
    ],
  },

  {
    slug: 'acceptable-use',
    navLabel: 'User Policy',
    title: 'Acceptable Use Policy',
    effectiveDate: '01/01/2025',
    blocks: [
      p('This Acceptable Use Policy explains the permitted and prohibited ways in which users may access and use the Auzyem online academic manuscript review platform ("Service").'),
      p('This Policy forms part of our Terms of Service. By using the Service, you agree to comply with this Policy.'),
      p('Our aim is to provide a reliable, secure and fair service for all users. We reserve the right to restrict or suspend access where use of the Service negatively impacts security, availability or the experience of other users.'),

      h('1. Purpose of the Service'),
      p('The Service is designed to provide educational feedback and analysis on academic manuscripts and written work.'),
      p('Users may use the Service to:'),
      ul([
        'receive feedback on their own academic writing',
        'identify opportunities for improvement',
        'strengthen structure, reasoning and analysis',
        'support their own learning and development',
      ]),
      p('The Service must be used in accordance with our Academic Integrity & Responsible Use Policy.'),

      h('2. Fair and Reasonable Usage'),
      p('Subscription plans provide access to the Service features described at the time of purchase.'),
      p('Access is subject to reasonable usage limits to ensure:'),
      ul([
        'reliable performance',
        'availability for all users',
        'protection against misuse',
        'sustainable operation of the platform',
      ]),
      p('We do not guarantee unlimited processing, uploads or usage unless a specific plan expressly states otherwise.'),
      p('We may apply reasonable restrictions where usage significantly exceeds typical user behaviour or impacts the performance of the Service.'),

      h('3. Examples of Excessive Usage'),
      p('Examples of usage that may be considered excessive include:'),
      ul([
        'repeatedly uploading unusually large volumes of manuscripts within a short period',
        'automated or bulk submissions',
        'attempting to use the Service as an API or automated processing system without permission',
        'sharing account access with multiple individuals',
        'creating multiple accounts to avoid usage limits',
        'using the Service in a way that negatively affects other users',
      ]),

      h('4. Prohibited Activities'),
      p('You must not use the Service to:'),
      h('Security and Technical Misuse'),
      ul([
        'attempt to gain unauthorised access to the Service, systems or accounts',
        'introduce viruses, malware or harmful code',
        'interfere with the operation or security of the platform',
        'probe, scan or test vulnerabilities without permission',
        'attempt to bypass security measures or usage restrictions',
      ]),
      h('Intellectual Property Misuse'),
      p('You must not:'),
      ul([
        'copy, reproduce or distribute the Service',
        'extract or replicate the underlying technology',
        'use the Service to develop a competing product',
        'reverse engineer, decompile or attempt to discover the source code or AI models',
      ]),
      h('Content Restrictions'),
      p('You must not upload content that:'),
      ul([
        'you do not have permission to use',
        "infringes another person's intellectual property rights",
        'contains unlawful material',
        'contains confidential information belonging to another person or organisation without authorisation',
        'contains malicious software or harmful content',
      ]),

      h('5. Account Sharing'),
      p('Accounts are intended for individual use unless a separate organisational agreement has been entered into.'),
      p('You must not:'),
      ul([
        'share your login credentials',
        'allow others to access your account',
        'resell access to the Service',
        'use one account on behalf of multiple users',
      ]),

      h('6. Automated Access'),
      p('The Service is intended for individual users accessing the platform through normal website functionality.'),
      p('You must not use:'),
      ul(['bots', 'scripts', 'automated upload tools', 'scraping tools', 'other automated systems']),
      p('to access, extract data from or interact with the Service unless expressly authorised by us.'),

      h('7. Uploaded Content'),
      p('You are responsible for ensuring that any content uploaded to the Service:'),
      ul([
        'belongs to you or you have permission to upload it',
        'does not breach any confidentiality obligations',
        'complies with applicable laws and institutional requirements',
      ]),
      p('You remain responsible for all manuscripts and materials submitted through your account.'),

      h('8. Monitoring and Enforcement'),
      p('We may monitor usage patterns to:'),
      ul(['maintain security', 'prevent fraud and abuse', 'ensure fair access', 'improve Service performance']),
      p('Where we reasonably believe this Policy has been breached, we may:'),
      ul(['issue a warning', 'limit access to certain features', 'temporarily suspend an account', 'terminate an account']),
      p('Where possible, we will seek to resolve concerns before taking enforcement action.'),

      h('9. Changes to Usage Limits'),
      p('We may update usage limits, restrictions or technical requirements from time to time.'),
      p('Where changes materially affect paid subscription users, we will provide reasonable notice where practicable.'),

      h('10. Contact Us'),
      p('If you have questions about this Acceptable Use Policy:'),
      contact('info@auzyem.com', 'www.auzyem.com'),
    ],
  },

  {
    slug: 'privacy',
    navLabel: 'Privacy Policy',
    title: 'Privacy Policy',
    effectiveDate: '01/01/2025',
    blocks: [
      p('At Auzyem ("we", "our", "us"), we respect your privacy and are committed to protecting your personal information.'),
      p('This Privacy Policy explains how we collect, use, store and protect information when you access or use our online academic manuscript review platform ("Service").'),
      p('This Policy applies to users worldwide. Where local privacy laws provide additional rights or protections, we will comply with those requirements.'),

      h('1. Information We Collect'),
      p('We may collect the following categories of information.'),
      h('1.1 Account Information'),
      p('When you create an account, we may collect:'),
      ul([
        'name',
        'email address',
        'password or authentication information',
        'country or region',
        'subscription information',
        'payment information (processed through third-party payment providers)',
      ]),
      h('1.2 Manuscripts and Uploaded Content'),
      p('When you use the Service, you may upload academic manuscripts, drafts or other written materials ("Content").'),
      p('This Content may include:'),
      ul([
        'manuscript text',
        'research information',
        'academic subject matter',
        'references and citations',
        'embedded information contained within uploaded documents',
      ]),
      p('We process uploaded Content solely to provide the manuscript review and feedback services requested by you.'),
      p('You retain ownership of all Content you upload.'),
      h('1.3 Usage Information'),
      p('We may automatically collect information about how you use the Service, including:'),
      ul([
        'pages visited',
        'features used',
        'subscription activity',
        'device information',
        'browser type',
        'IP address',
        'system activity logs',
      ]),
      p('This information helps us maintain security, improve performance and understand how users interact with the Service.'),

      h('2. How We Use Your Information'),
      p('We may use your information to:'),
      ul([
        'create and manage your account',
        'provide manuscript review and feedback services',
        'process payments',
        'communicate with you about your account',
        'provide customer support',
        'improve the Service',
        'monitor security and prevent misuse',
        'comply with legal obligations',
      ]),

      h('3. How We Process and Store Manuscripts'),
      p('When you upload a manuscript or other written material, your Content is securely processed to provide manuscript analysis, feedback and related features.'),
      p('To provide features such as review history, progress tracking and access to previous submissions, we may store uploaded Content within your account.'),
      p('Your Content:'),
      ul([
        'remains your property',
        'is not published or made publicly available',
        'is not shared with other users',
        'is not sold or licensed to third parties',
        'is not used to create academic content on your behalf',
      ]),
      p('You may request deletion of your uploaded Content or account as described in this Privacy Policy.'),

      h('4. Artificial Intelligence Processing'),
      p('The Service uses artificial intelligence technologies to analyse manuscripts and provide feedback.'),
      p('By using the Service, you acknowledge that:'),
      ul([
        'your uploaded Content may be processed using AI systems',
        'feedback is generated through automated analysis',
        'AI-generated feedback may not always be complete or accurate',
      ]),
      p('We apply appropriate measures designed to protect user Content and maintain the security of the Service.'),

      h('5. Use of Data for Service Improvement'),
      p('The Service uses artificial intelligence technologies to analyse manuscripts and provide feedback.'),
      p('Your uploaded Content may be processed by AI systems solely for the purpose of providing the Service.'),
      p('We may use anonymised and aggregated information about Service usage to improve the performance, reliability and quality of the platform.'),
      p('We do not use identifiable manuscripts, personal academic work or user Content to train AI models unless we clearly disclose this practice and obtain any consent required under applicable law.'),

      h('6. Payment Information'),
      p('Payments are processed through trusted third-party payment providers.'),
      p('We do not store complete payment card details.'),
      p('Payment providers process your information in accordance with their own privacy policies and security practices.'),

      h('7. Cookies and Similar Technologies'),
      p('We may use cookies and similar technologies to:'),
      ul(['maintain account functionality', 'remember user preferences', 'analyse usage patterns', 'improve website performance']),
      p('Users may manage cookie preferences through their browser settings or available cookie controls.'),

      h('8. Sharing Your Information'),
      p('We do not sell your personal information.'),
      p('We may share information only where necessary with:'),
      h('Service Providers'),
      p('Trusted third parties that support our operations, including:'),
      ul(['hosting providers', 'payment processors', 'authentication providers', 'analytics providers', 'customer support platforms']),
      p('These providers are contractually required to protect your information.'),
      h('Legal Requirements'),
      p('We may disclose information where required by law, regulation, court order or governmental authority.'),

      h('9. International Data Transfers'),
      p('Because the Service is available globally, your information may be processed or stored in countries outside your country of residence.'),
      p('Where information is transferred internationally, we take reasonable steps to ensure appropriate safeguards are in place.'),

      h('10. Data Security'),
      p('We implement reasonable technical and organisational measures designed to protect your information against:'),
      ul(['unauthorised access', 'accidental loss', 'misuse', 'alteration', 'disclosure']),
      p('However, no online service can guarantee absolute security.'),

      h('11. Data Retention and Deletion'),
      p('We retain your account information and uploaded Content for as long as necessary to provide the Service and maintain features such as manuscript history and previous feedback.'),
      p('You may delete uploaded manuscripts or request deletion of your account through the available account controls or by contacting us.'),
      p('When deletion is requested, we will take reasonable steps to remove your information from active systems, subject to:'),
      ul(['legal requirements', 'security backups', 'technical limitations', 'legitimate business requirements']),
      p('Backup copies may remain temporarily before being securely deleted in accordance with our retention processes.'),

      h('12. Your Privacy Rights'),
      p('Depending on where you live, you may have rights including:'),
      ul([
        'access to your personal information',
        'correction of inaccurate information',
        'deletion of your information',
        'restriction of processing',
        'objection to certain processing',
        'receiving a copy of your data',
      ]),
      p('Requests can be submitted using the contact details below.'),

      h("13. Children's Privacy"),
      p('The Service is not intended for users under the age of 18 unless they have appropriate legal authority to enter into an agreement.'),
      p('We do not knowingly collect personal information from children.'),

      h('14. Changes to This Privacy Policy'),
      p('We may update this Privacy Policy from time to time.'),
      p('Where changes are significant, we will provide reasonable notice through the Service or by email.'),

      h('15. Contact Us'),
      p('If you have questions about this Privacy Policy or how we handle your information:'),
      contact('info@auzyem.com', 'www.auzyem.com'),
    ],
  },

  {
    slug: 'terms-of-service',
    navLabel: 'Terms of Service',
    title: 'Terms of Service',
    effectiveDate: '01/01/2025',
    blocks: [
      p('Welcome to Auzyem ("we", "our", "us").'),
      p('These Terms of Service ("Terms") govern your access to and use of our online academic manuscript review platform ("Service"). By creating an account, accessing or using the Service, you agree to be legally bound by these Terms.'),
      p('If you do not agree with these Terms, you must not use the Service.'),

      h('1. Purpose of the Service'),
      p('The Service provides automated educational feedback on academic manuscripts and other written work submitted by users.'),
      p('The Service is designed to identify strengths, weaknesses and opportunities for improvement in academic writing. The Service is intended to support users in developing and improving their own work.'),
      p('The Service does not generate academic assignments on behalf of users, complete coursework, or guarantee any academic outcome.'),

      h('2. Eligibility'),
      p('To use the Service you must:'),
      ul([
        'be at least 18 years of age, or have the legal capacity to enter into a binding agreement under the laws of your country',
        'provide accurate registration information',
        'comply with these Terms at all times',
      ]),
      p('If you are using the Service on behalf of an organisation, you confirm that you have authority to bind that organisation to these Terms.'),

      h('3. User Accounts'),
      p('You are responsible for:'),
      ul([
        'maintaining the confidentiality of your login credentials',
        'all activity occurring under your account',
        'promptly notifying us of any unauthorised access',
      ]),
      p('We reserve the right to suspend or terminate accounts where we reasonably believe these Terms have been breached.'),

      h('4. Subscription Services'),
      p('Certain features of the Service require a paid subscription.'),
      p('Subscription plans, pricing and available features are published on our website and may change from time to time.'),
      p('Unless otherwise stated:'),
      ul([
        'subscriptions automatically renew',
        'payment is collected in advance',
        'subscriptions continue until cancelled',
        'cancellation prevents future renewals but does not normally entitle users to refunds for the current billing period',
      ]),
      p('Applicable consumer protection laws in your jurisdiction may provide additional rights.'),

      h('5. Free and Promotional Access'),
      p('We may offer a free manuscript review or other promotional access.'),
      p('We reserve the right to withdraw, modify or discontinue free offers at any time.'),

      h('6. Acceptable Use'),
      p('You agree not to:'),
      ul([
        'upload unlawful material',
        'upload malicious software',
        'upload material that infringes copyright',
        'upload confidential documents you are not authorised to disclose',
        'interfere with the operation or security of the Service',
        'attempt to reverse engineer or copy the Service',
        'use automated tools to access the Service except where expressly authorised',
      ]),

      h('7. Ownership of Your Content'),
      p('You retain ownership of all manuscripts, documents and other content you upload.'),
      p('By uploading content, you grant us a limited, worldwide, non-exclusive licence to store, process, analyse and display your content solely for the purpose of providing and improving the Service.'),
      p('Except where expressly permitted by our Privacy Policy or with your consent, we will not sell your uploaded manuscripts.'),

      h('8. Academic Integrity'),
      p('The Service is intended solely as an educational feedback tool.'),
      p('Users remain entirely responsible for:'),
      ul([
        'all submitted work',
        'compliance with university regulations',
        'compliance with academic integrity policies',
        'all decisions regarding whether and how to implement feedback',
      ]),
      p('Use of the Service does not imply approval by any university, college or educational institution.'),
      p('The Service should not be used to misrepresent authorship or to circumvent academic integrity requirements.'),

      h('9. AI-Generated Feedback'),
      p('Feedback is generated using artificial intelligence and automated analytical systems.'),
      p('Although we continually seek to improve the quality of the Service:'),
      ul([
        'feedback may contain inaccuracies',
        'feedback may not identify every issue',
        'different reviewers may reasonably reach different conclusions',
      ]),
      p('Users should exercise independent academic judgement before implementing any recommendations.'),

      h('10. Intellectual Property'),
      p('All intellectual property rights in the Service, including but not limited to the software, website, algorithms, artificial intelligence models, databases, designs, trademarks, branding, text, graphics and underlying technology, are owned by or licensed to Auzyem.'),
      p('Except as expressly permitted by these Terms, you may not:'),
      ul([
        'copy, reproduce or distribute any part of the Service',
        'modify, adapt or create derivative works from the Service',
        'reverse engineer, decompile or attempt to discover the source code or underlying models of the Service',
        'use the Service to develop or train a competing product or service',
        'remove or alter any copyright, trademark or proprietary notices',
      ]),
      p('Nothing in these Terms transfers ownership of any intellectual property rights to you.'),

      h('11. Service Availability'),
      p('We aim to provide the Service continuously; however, we do not guarantee uninterrupted or error-free access.'),
      p('From time to time, the Service may be unavailable due to:'),
      ul([
        'scheduled maintenance',
        'emergency maintenance',
        'software updates',
        'security incidents',
        'failures of third-party providers',
        'events beyond our reasonable control',
      ]),
      p('We reserve the right to modify, suspend or discontinue any feature of the Service at any time.'),
      p('Where reasonably practicable, we will provide advance notice of planned maintenance.'),

      h('12. Disclaimer of Warranties'),
      p('The Service is provided on an "as is" and "as available" basis.'),
      p('To the fullest extent permitted by applicable law, we make no representations or warranties, whether express or implied, including but not limited to warranties that:'),
      ul([
        'the Service will be uninterrupted or error-free',
        "the Service will meet every user's individual requirements",
        'feedback will always be accurate, complete or suitable for a particular academic discipline',
        'use of the Service will improve academic performance or grades',
        'use of the Service will satisfy the requirements of any university, college, employer or professional body',
      ]),
      p('Users acknowledge that academic judgement remains subjective and that feedback generated by the Service is intended solely as educational guidance.'),

      h('13. Limitation of Liability'),
      p('To the fullest extent permitted by applicable law, Auzyem, its directors, employees, contractors and affiliates shall not be liable for any indirect, incidental, consequential, exemplary, punitive or special damages arising from or relating to the use of the Service.'),
      p('This includes, but is not limited to:'),
      ul([
        'loss of academic marks or grades',
        'failed assignments',
        'failed dissertations',
        'examination failures',
        'delayed submissions',
        'academic misconduct investigations',
        'loss of scholarships or funding',
        'visa consequences',
        'employment or career impacts',
        'loss of profits',
        'business interruption',
        'reputational damage',
        'loss of data',
      ]),
      p('Our total aggregate liability arising from or relating to the Service shall not exceed the total subscription fees paid by you during the twelve (12) months immediately preceding the event giving rise to the claim.'),
      p('Nothing in these Terms excludes liability that cannot legally be excluded under applicable law, including liability for fraud, fraudulent misrepresentation, or death or personal injury caused by negligence where such exclusion is prohibited.'),

      h('14. User Indemnity'),
      p('You agree to indemnify and hold harmless Auzyem, its directors, employees, contractors, affiliates and licensors from any claims, liabilities, damages, costs or expenses (including reasonable legal fees) arising from:'),
      ul([
        'your breach of these Terms',
        'your misuse of the Service',
        'your violation of applicable laws or regulations',
        'infringement of third-party intellectual property rights through content you upload',
        'any dispute between you and your educational institution arising from your use of the Service',
      ]),

      h('15. Suspension and Termination'),
      p('We may suspend or terminate your account immediately where we reasonably believe that:'),
      ul([
        'you have breached these Terms',
        'you have engaged in fraudulent or unlawful activity',
        'you have attempted to compromise the security of the Service',
        'your use presents a risk to other users or to the integrity of the Service',
      ]),
      p('You may cancel your subscription at any time through your account settings.'),
      p('Termination of your account does not affect any rights or obligations that arose before termination.'),
      p('We may retain certain information where required by law or as described in our Privacy Policy.'),

      h('16. Changes to the Service'),
      p('We continually develop and improve the Service and reserve the right to modify, enhance, replace, suspend or discontinue any feature, functionality or part of the Service at any time.'),
      p('We may introduce new features, modify existing features or remove features where reasonably necessary to improve performance, security, compliance or user experience.'),
      p('Where changes materially affect paid subscribers, we will endeavour to provide reasonable notice.'),

      h('17. Changes to these Terms'),
      p('We may amend these Terms from time to time.'),
      p('Where changes are material, we will notify users by email, through the Service or by another reasonable method before the updated Terms take effect.'),
      p('Your continued use of the Service after the effective date of any updated Terms constitutes acceptance of those changes.'),
      p('If you do not agree to the revised Terms, you must stop using the Service and cancel your subscription.'),

      h('18. Privacy'),
      p('Your use of the Service is also governed by our Privacy Policy.'),
      p('The Privacy Policy explains how we collect, use, store and protect your personal information and uploaded content.'),
      p('By using the Service, you acknowledge that you have read our Privacy Policy.'),

      h('19. Third-Party Services'),
      p('The Service may integrate with or rely upon third-party providers, including but not limited to cloud hosting providers, payment processors, authentication providers and analytics services.'),
      p('We are not responsible for the availability, security, content or practices of third-party services.'),
      p("Your use of any third-party service is governed by that provider's own terms and policies."),

      h('20. Force Majeure'),
      p('We shall not be liable for any delay or failure to perform our obligations where such delay or failure results from events beyond our reasonable control.'),
      p('Such events may include, but are not limited to:'),
      ul([
        'natural disasters',
        'war',
        'terrorism',
        'civil unrest',
        'governmental action',
        'labour disputes',
        'internet or telecommunications failures',
        'cyber attacks',
        'widespread outages of cloud infrastructure providers',
        'pandemics or public health emergencies',
      ]),
      p('Performance of our obligations will be suspended for the duration of the event.'),

      h('21. Assignment'),
      p('You may not assign or transfer your rights or obligations under these Terms without our prior written consent.'),
      p('We may assign or transfer our rights and obligations under these Terms as part of a merger, acquisition, corporate restructuring or sale of all or substantially all of our assets.'),

      h('22. Entire Agreement'),
      p('These Terms, together with our Privacy Policy, Acceptable Use Policy and any other policies expressly incorporated by reference, constitute the entire agreement between you and us regarding the Service.'),
      p('They supersede all prior discussions, communications and understandings relating to the Service.'),

      h('23. Severability'),
      p('If any provision of these Terms is found by a court or competent authority to be unlawful, invalid or unenforceable, the remaining provisions shall remain in full force and effect.'),
      p('The invalid provision shall, where possible, be interpreted so as to achieve its original commercial purpose while remaining legally enforceable.'),

      h('24. No Waiver'),
      p('Failure or delay by either party to enforce any provision of these Terms shall not constitute a waiver of that provision or any other rights.'),
      p('Any waiver must be made expressly in writing.'),

      h('25. Governing Law'),
      p('These Terms shall be governed by and interpreted in accordance with the laws of England and Wales, unless mandatory consumer protection laws in your country of residence require otherwise.'),
      p('Where legally permitted, the courts of England and Wales shall have exclusive jurisdiction over any dispute arising from or relating to these Terms or the Service.'),
      p('Nothing in these Terms limits any mandatory legal rights available to consumers under applicable law.'),

      h('26. Contact Information'),
      p('If you have any questions regarding these Terms, please contact us:'),
      contact('info@auzyem.com', 'www.auzyem.com'),

      h('27. Service Improvement'),
      p('We may use anonymised and aggregated usage information to improve the performance, reliability and accuracy of the Service.'),
      p('We will not use your identifiable manuscript content to train artificial intelligence models unless this is expressly disclosed in our Privacy Policy or you have provided any consent required by applicable law.'),

      h('28. Educational Purpose'),
      p('The feedback provided by the Service is intended solely to assist users in developing their own academic writing.'),
      p('Feedback should not be interpreted as predicting marks, grades, classifications or examination outcomes, and users should not rely on it as a substitute for guidance from supervisors, tutors or educational institutions.'),
    ],
  },

  {
    slug: 'cookies',
    navLabel: 'Cookie Policy',
    title: 'Cookie Policy',
    effectiveDate: '01/01/2025',
    blocks: [
      p('This Cookie Policy explains how Auzyem ("we", "our", "us") uses cookies and similar technologies when you visit our website or use our online academic manuscript review platform ("Service").'),
      p('This Cookie Policy should be read alongside our Privacy Policy, which explains how we collect, use and protect personal information.'),

      h('1. What Are Cookies?'),
      p('Cookies are small text files placed on your device when you visit a website.'),
      p('Cookies allow websites to recognise your device, remember preferences, improve functionality and understand how users interact with online services.'),
      p('We may also use similar technologies, such as pixels, tags and local storage, which perform similar functions.'),

      h('2. How We Use Cookies'),
      h('2.1 Essential Cookies'),
      p('These cookies are necessary for the Service to function properly.'),
      p('They may be used to:'),
      ul([
        'authenticate users',
        'keep users securely logged into their account',
        'maintain account sessions',
        'process subscription access',
        'protect against fraud and security threats',
        'enable core website functionality',
      ]),
      p('These cookies cannot generally be disabled because the Service may not function correctly without them.'),

      h('2.2 Functional Cookies'),
      p('These cookies allow us to remember user preferences and improve the experience.'),
      p('They may help us remember:'),
      ul(['language preferences', 'account settings', 'previous choices', 'user interface preferences']),

      h('2.3 Analytics Cookies'),
      p('These cookies help us understand how users interact with the Service.'),
      p('We may use analytics cookies to understand:'),
      ul(['which pages users visit', 'how users discover the platform', 'which features are used', 'website performance', 'areas for improvement']),
      p('Analytics data is generally analysed in an aggregated or anonymised form.'),

      h('2.4 Marketing and Advertising Cookies'),
      p('Where applicable, we may use marketing cookies to:'),
      ul([
        'measure the effectiveness of marketing campaigns',
        'understand visitor journeys',
        'provide relevant communications',
        'evaluate advertising performance',
      ]),
      p('These cookies may be provided by approved third-party services.'),

      h('3. Third-Party Cookies'),
      p('Some cookies may be placed by third-party service providers who support our operations.'),
      p('These providers may include services relating to:'),
      ul(['payments', 'authentication', 'website analytics', 'customer support', 'security monitoring', 'marketing platforms']),
      p('Third parties may process information according to their own privacy policies.'),
      p('We encourage you to review the privacy practices of any third-party services used through the Service.'),

      h('4. Managing Cookies'),
      p('You can control or delete cookies through your browser settings.'),
      p('Most browsers allow you to:'),
      ul(['view stored cookies', 'delete cookies', 'block cookies', 'receive warnings before cookies are stored']),
      p('Please note that disabling certain cookies may affect the functionality or availability of parts of the Service.'),

      h('5. Cookie Consent'),
      p('Where required by applicable law, we will request your consent before placing non-essential cookies on your device.'),
      p('You may change or withdraw your cookie preferences at any time through available cookie controls or your browser settings.'),

      h('6. International Users'),
      p('Because our Service is available globally, cookie requirements may vary depending on your location.'),
      p('We take reasonable steps to comply with applicable privacy and cookie regulations, including requirements that may apply in regions such as:'),
      ul(['the United Kingdom', 'the European Economic Area', 'California', 'other jurisdictions where applicable']),

      h('7. Changes to This Cookie Policy'),
      p('We may update this Cookie Policy from time to time to reflect changes in:'),
      ul(['technology', 'legal requirements', 'the features available through the Service', 'third-party services we use']),
      p('Any updates will be posted on this page with a revised effective date.'),

      h('8. Contact Us'),
      p('If you have questions about this Cookie Policy:'),
      contact('info@auzyem.com', 'www.auzyem.com'),
    ],
  },

  {
    slug: 'subscription-refund',
    navLabel: 'Subscription & Refund Policy',
    title: 'Subscription & Refund Policy',
    effectiveDate: '01/01/2025',
    blocks: [
      p('This Subscription & Refund Policy explains the subscription plans, payments, renewals, cancellations and refunds relating to the Auzyem online manuscript review platform ("Service").'),
      p('This Policy forms part of our Terms of Service.'),

      h('1. Subscription Plans'),
      p('We offer subscription plans that provide access to additional Service features beyond any free access or promotional offering.'),
      p('Details of available plans, features and pricing are displayed on our website at the time of purchase.'),
      p('Subscription plans may include, depending on the selected plan:'),
      ul([
        'access to manuscript review functionality',
        'access to previous reviews',
        'manuscript history',
        'additional usage allowances',
        'other features made available from time to time',
      ]),
      p('We reserve the right to introduce, modify or discontinue subscription plans and features.'),

      h('2. Free and Promotional Access'),
      p('We may offer free access or promotional offers from time to time.'),
      p('Unless otherwise stated:'),
      ul([
        'free access is limited to the features and usage limits specified',
        'free access does not create any obligation for us to continue providing free access',
        'promotional offers may be subject to additional terms',
      ]),
      p('Free access does not convert automatically into a paid subscription. Paid plans begin only when you choose one and are charged from the start of the subscription.'),

      h('3. Payment Terms'),
      p('Paid subscriptions are charged in advance on a recurring basis according to the billing frequency selected at purchase.'),
      p('Payments may be processed by third-party payment providers.'),
      p('You agree to:'),
      ul(['provide accurate billing information', 'ensure payment details remain current', 'authorise recurring charges where applicable']),
      p('Prices may be displayed in different currencies depending on your location or payment provider.'),
      p('Any applicable taxes, including sales tax, VAT or similar charges, may be added where required by law.'),

      h('4. Automatic Renewal'),
      p('Subscriptions automatically renew at the end of each billing period unless cancelled before the renewal date.'),
      p('By subscribing, you authorise us or our payment provider to charge your payment method for future subscription periods.'),
      p('We will provide information about renewal terms at the point of purchase.'),

      h('5. Cancelling Your Subscription'),
      p('You may cancel your subscription at any time through your account settings or by contacting customer support.'),
      p('Cancellation will take effect at the end of your current paid billing period.'),
      p('After cancellation:'),
      ul([
        'you will continue to have access until the end of the period already paid for',
        'you will not be charged for future renewal periods',
        'your account and stored Content will be handled in accordance with our Privacy Policy',
      ]),
      p('Cancelling your subscription does not automatically delete your account or uploaded manuscripts unless you request deletion.'),

      h('6. Refund Policy'),
      p('We want users to have confidence in the Service. Refund requests will be considered fairly, taking into account applicable consumer protection laws.'),
      p('Except where required by law, subscription payments are generally non-refundable once a billing period has started.'),
      p('This is because the Service provides immediate access to digital features and processing capabilities.'),

      h('7. Refund Exceptions'),
      p('We may provide refunds where:'),
      ul([
        'there was an error in payment processing',
        'the subscription was purchased accidentally and the request is made promptly',
        'the Service was unavailable for a significant period due to an issue within our control',
        'required under applicable consumer protection laws',
      ]),
      p('Refund decisions are made on a case-by-case basis.'),

      h('8. Digital Services and Immediate Access'),
      p('By purchasing a subscription, you acknowledge that:'),
      ul([
        'access to digital services begins immediately',
        'you may lose any statutory cancellation rights that apply to digital content once performance has begun, where permitted by law',
        'the Service provides immediate access to features upon successful payment',
      ]),
      p('Nothing in this section limits rights that cannot legally be excluded.'),

      h('9. Failed Payments'),
      p('If payment cannot be processed, we may:'),
      ul(['retry the payment method', 'request updated payment information', 'temporarily restrict access to paid features', 'suspend or cancel the subscription']),
      p('We are not responsible for interruptions caused by payment provider failures or outdated payment information.'),

      h('10. Price Changes'),
      p('We may change subscription pricing from time to time.'),
      p('If we increase the price of an existing subscription, we will provide reasonable notice before the change takes effect.'),
      p('Where required by law, you will have the opportunity to cancel before the new price applies.'),

      h('11. Promotions and Discounts'),
      p('Promotional pricing, discounts or offers may be subject to additional conditions.'),
      p('Unless otherwise stated:'),
      ul(['promotional prices apply only for the specified period', 'discounts cannot be combined', 'we reserve the right to withdraw promotional offers']),

      h('12. Contact Us'),
      p('If you have questions regarding subscriptions, payments or refunds:'),
      contact('info@auzyem.com', 'www.auzyem.com'),
    ],
  },

  {
    slug: 'faq',
    navLabel: 'FAQ',
    title: 'Frequently Asked Questions',
    effectiveDate: null,
    blocks: [
      h('Is this an AI writing tool?'),
      p('No. The platform does not write dissertations, create assignments or replace your own academic work.'),
      p('It acts as a reviewer, identifying areas where your manuscript could be improved.'),

      h('Will this write my dissertation for me?'),
      p('No.'),
      p('The purpose of the platform is to provide feedback, similar to receiving comments from a peer reviewer or academic mentor.'),
      p('You remain responsible for your own work.'),

      h('Will my university know I used this?'),
      p('The platform does not notify universities or share your information with educational institutions.'),
      p("However, you are responsible for understanding and following your university's own policies regarding the use of AI tools."),

      h('Is my dissertation used to train AI?'),
      p('Your uploaded manuscript is not used to train AI models unless we clearly inform you and obtain any required permission.'),

      h('Who can see my manuscript?'),
      p('Your manuscript is private to your account and is not visible to other users.'),

      h('Does this guarantee a better grade?'),
      p('No.'),
      p('The tool identifies potential improvements, but academic assessment involves human judgement and no tool can predict or guarantee grades.'),

      h('Why should I use this instead of ChatGPT?'),
      p('A general AI assistant can help with many tasks, but this platform has been specifically designed to review academic manuscripts and provide structured feedback focused on improving your work.'),

      h('How many manuscripts can I review?'),
      p('Your plan includes access to manuscript reviews subject to reasonable usage limits designed to ensure a reliable experience for all users. We do not believe in artificial restrictions, but we may intervene where usage is significantly outside normal student requirements.'),
    ],
  },
]

export function getLegalDoc(slug: string): LegalDoc | undefined {
  return LEGAL_DOCS.find(d => d.slug === slug)
}
